<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7b4f2a4eb7dbba5c3426411201c12a4d
{
    public static $files = array (
        'decc78cc4436b1292c6c0d151b19445c' => __DIR__ . '/../..' . '/phpseclib/bootstrap.php',
        '5255c38a0faeba867671b61dfda6d864' => __DIR__ . '/..' . '/paragonie/random_compat/lib/random.php',         
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpseclib3\\' => 11,
        ),
        'P' => 
        array (
            'ParagonIE\\ConstantTime\\' => 23,
        ),
        
    );

    public static $prefixDirsPsr4 = array (
        'phpseclib3\\' => 
        array (
            0 => __DIR__ . '/../..' . '/phpseclib',
        ), 
        'ParagonIE\\ConstantTime\\' => 
        array (
            0 => __DIR__ . '/..' . '/paragonie/constant_time_encoding/src',
        ),      
    );

    public static $prefixesPsr0 = array (
    );

    public static $classMap = array (
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7b4f2a4eb7dbba5c3426411201c12a4d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7b4f2a4eb7dbba5c3426411201c12a4d::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit7b4f2a4eb7dbba5c3426411201c12a4d::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit7b4f2a4eb7dbba5c3426411201c12a4d::$classMap;

        }, null, ClassLoader::class);
    }
}
